# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter:             postgresql
  encoding:            unicode
  reconnect:           true
  pool:             20
  schema_search_path:  public
  host:     <%= ENV['PB_DB_HOST'] %>
  port:     <%= ENV['PB_DB_PORT'] %>
  database: <%= ENV['PB_DB_NAME'] %>
  username: <%= ENV['PB_DB_USER'] %>
  password: <%= ENV['PB_DB_PASS'] %>

development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
